[colors.bright]
black = "#6E6C7E"
blue = "#A4B9EF"
cyan = "#E5B4E2"
green = "#B1E3AD"
magenta = "#C6AAE8"
red = "#E38C8F"
white = "#DADAE8"
yellow = "#EBDDAA"

[colors.normal]
black = "#6E6C7E"
blue = "#A4B9EF"
cyan = "#E5B4E2"
green = "#B1E3AD"
magenta = "#C6AAE8"
red = "#E38C8F"
white = "#DADAE8"
yellow = "#EBDDAA"

[colors.primary]
background = "#222222"
foreground = "#DADAE8"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[window.padding]
x = 15
y = 15
